/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TourRouteImport } from './routes/tour'
import { Route as MusicIndexRouteImport } from './routes/music/index'
import { Route as MusicSlugRouteImport } from './routes/music/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicSlugRoute = MusicSlugRouteImport.update({
  id: '/music/$slug',
  path: '/music/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/story': typeof StoryRoute
  '/tour': typeof TourRoute
  '/music/$slug': typeof MusicSlugRoute
  '/music/': typeof MusicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/story': typeof StoryRoute
  '/tour': typeof TourRoute
  '/music/$slug': typeof MusicSlugRoute
  '/music': typeof MusicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/story': typeof StoryRoute
  '/tour': typeof TourRoute
  '/music/$slug': typeof MusicSlugRoute
  '/music/': typeof MusicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/story'
    | '/tour'
    | '/music/$slug'
    | '/music/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community'
    | '/story'
    | '/tour'
    | '/music/$slug'
    | '/music'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/story'
    | '/tour'
    | '/music/$slug'
    | '/music/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  StoryRoute: typeof StoryRoute
  TourRoute: typeof TourRoute
  MusicSlugRoute: typeof MusicSlugRoute
  MusicIndexRoute: typeof MusicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/$slug': {
      id: '/music/$slug'
      path: '/music/$slug'
      fullPath: '/music/$slug'
      preLoaderRoute: typeof MusicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  StoryRoute: StoryRoute,
  TourRoute: TourRoute,
  MusicSlugRoute: MusicSlugRoute,
  MusicIndexRoute: MusicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
